[package]
name = "evento-derive"
version = "0.1.0"
authors = ["Ricardo Gamba Lavin <gamba@fb.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15.44", features = ["full"]}
quote = "0.6.10"
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0"